### ISSUE TITLE
Inquiry Regarding GPU Memory and Number Requirements and Training Duration

### ISSUE THREAD

**Issue by hero-y** [algvr/transfusion#1]
I have a few questions regarding the computational resources required to do so.

1.GPU Memory Requirement: Could you please specify the amount of GPU memory required for training the models discussed in the paper? I would appreciate knowing if there are any specific GPU models that are recommended.

2.Number of GPUs: How many GPUs are needed to achieve the results presented in the paper? If it's scalable, could you provide a guideline on how the number of GPUs might affect the training process?

3.Training Duration: What is the approximate training time for the models using the recommended setup? Is this time frame based on a specific GPU configuration?

**Comment by algvr** [comment]
Hi hero-y,

for Ego4Dv1, our base model can be trained on one NVIDIA A100 GPU (80GB) using 16-bit precision and two such GPUs using 32-bit precision. For Ego4Dv2, those numbers are two and three NVIDIA A100 GPUs for 16-bit and 32-bit precision, respectively. Note that training with 16-bit precision has been observed to occasionally result in numerical instabilities.

The training duration is about 16 hours at most for each dataset version, using the aforementioned GPUs and starting with the Ego4D-provided ResNet backbone. While using more but smaller GPUs should work as well, we did not test such a setup.

To obtain the results in the paper, you will further need to run (not train) the Ego4D SlowFast TTC predictor after running our model to replace the stock predicted TTC values. The Ego4D team kindly provides checkpoints for the predictor trained on Ego4Dv1/Ego4Dv2 in their official repository. See our README file for instructions.

All this assumes that you are working on the Ego4Dv1 and/or Ego4Dv2 dataset. Otherwise, having to train an extra visual backbone and TTC predictor will add to the training time.
